version: '3.6'

services:

  client:
    container_name: client
    build:
      context: .
      dockerfile: Dockerfile-dev
    volumes:
      - '.:/usr/src/app'
    ports:
      - '3007:3000' # expose ports - HOST:CONTAINER
    environment:
      - NODE_ENV=development
      - CI=${CI:-false}
      - REACT_APP_EVENTS_SERVICE_URL=${REACT_APP_EVENTS_SERVICE_URL}
      - REACT_APP_GOOGLE_ANALYTICS_ID=${REACT_APP_GOOGLE_ANALYTICS_ID:-UA-123052755-1}

  client-test:
    container_name: client-test
    build:
      context: .
      dockerfile: Dockerfile-dev
    environment:
      - NODE_ENV=development
      - CI=${CI:-false}
    volumes:
      - '.:/usr/src/app'
